### ISSUE TITLE
Memory leak found at main.c:90

### ISSUE THREAD

**Issue by Rrooach** [cloudwu/rudp#6]
Hello, I found a __MEMORY LEAK__  in main.c:90
__Below are steps followed to reproduce crash__
Download latest source code from: https://github.com/cloudwu/rudp, compiled with clang and ASAN```export CFLAGS="-g -fsanitize=address" LDFLAGS="-fsanitize=address"```before make

__ASAN Output__ 

```
=================================================================
==25482==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x4b8818  (/root/temp/ICS/rudp/rudp+0x4b8818)
    #1 0x4e9d94  (/root/temp/ICS/rudp/rudp+0x4e9d94)

SUMMARY: AddressSanitizer: 120 byte(s) leaked in 1 allocation(s).
```

it seems that you have a double free issue.

**Comment by cloudwu** [comment]
Thanks, it's a memory leak, but I don't think it's a double free issue.

**Comment by Rrooach** [comment]
I'm not familiar with your program structure, but it looks like that some space was not free properly, I will close this issue.
